# Task 44 - Gitlab CI Templates 

# 1. Update your .gitlab-ci.yml file to delete only and tags from all the jobs.
# 2. After that, import the template in all your jobs in the .gitlab-ci.yml file, 
#    so that they can use the only and tags from the template body.


include:
  - local: 'child-pipeline.yml' 

default: 
  timeout: 1 hour

stages:
  - pre-check
  - build
  - test
  - deploy 

image: docker:latest

.job_docker_template: &template # 1
  only:  
    - main

CI_Pre_Check:
  <<: *template
  stage: pre-check
  allow_failure: true 
  script:
    - docker version 
    - docker ps 
    - docker images ls 
    - sleep 20  
     
CI_Build:
  <<: *template
  stage: build
  needs: [] 
  retry: 2
  inherit:
    default: false 
  before_script:
    - echo "Build CI_Build Started"
    - sleep 10
  script:
    - docker build -t $Image_Name:$CI_PIPELINE_IID . 
    - docker save $Image_Name:$CI_PIPELINE_IID > $CI_PIPELINE_IID.tar 
  after_script:
    - docker images
  artifacts: 
    name: "Devops"
    paths:
      - ./ 
    when: on_failure  
    expire_in: 1 week 
    exclude:
      - .gitlab-ci.yml 

CI_Build_V2:
  <<: *template
  stage: build
  needs: [CI_Pre_Check] 
  before_script:
    - echo "Build CI_Build_V2 Started"
    - sleep 10
  script:
    - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
  after_script:
    - docker images

CI_Test:
  <<: *template
  stage: test
  when: manual 
  script:
    - docker ps
    - docker images
    
.pages: 
  <<: *template
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public

CI_Deploy_Testing: 
  <<: *template
  stage: deploy
  script:
    - docker run -itd -p 80:80 httpd
  environment:
    name: Testing
