# task 29 - Gitlab CI Artifacts

# 1. Update your CI_Build Job and remove "parallel: 2" section from the Job
# 2. Update the CI_Build Job and add one more command "sudo docker save $Image_Name:$CI_PIPELINE_IID > $CI_PIPELINE_IID.tar"

include:
  - local: 'child-pipeline.yml' 

default: 
  timeout: 1 hour

stages:
    - pre-check
    - build
    - test

image: docker:latest

CI_Pre_Check:
    stage: pre-check
    only: 
      - main
    allow_failure: true 
    script:
      - docker version 
      - docker ps 
      - docker images ls 
      - sleep 20  
     
CI_Build:
    stage: build
    needs: [] 
    retry: 2
    only: 
      - main
    before_script:
      - echo "Build CI_Build Started"
      - sleep 10
    script:
      - docker build -t $Image_Name:$CI_PIPELINE_IID . 
      - docker save $Image_Name:$CI_PIPELINE_IID > $CI_PIPELINE_IID.tar #2
    after_script:
      - docker images

CI_Build_V2:
    stage: build
    only:
      - main
    needs: [CI_Pre_Check] 
    before_script:
      - echo "Build CI_Build_V2 Started"
      - sleep 10
    script:
      - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Test:
    stage: test
    only:
      - main
    when: manual 
    script:
      - docker ps
      - docker images
