# Task 35 - Inherit

# 1. Update your CI_Build Job to disable the inheritance of all defaults in the Job.


include:
  - local: 'child-pipeline.yml' 

default: 
  timeout: 1 hour

stages:
    - pre-check
    - build
    - test

image: docker:latest

CI_Pre_Check:
    stage: pre-check
    image: docker
    only: 
      - main
    allow_failure: true 
    script:
      - docker version 
      - docker ps 
      - docker images ls 
      - sleep 20  
     
CI_Build:
    stage: build
    needs: [] 
    retry: 2
    inherit:
      default: false # 1. Disable the inheritance of all defaults in the Job.
    only: 
      - main
    before_script:
      - echo "Build CI_Build Started"
      - sleep 10
    script:
      - docker build -t $Image_Name:$CI_PIPELINE_IID . 
      - docker save $Image_Name:$CI_PIPELINE_IID > $CI_PIPELINE_IID.tar 
    after_script:
      - docker images
    artifacts: 
      name: "Devops"
      paths:
        - ./ 
      when: on_failure  
      expire_in: 1 week 
      exclude:
        - .gitlab-ci.yml 

CI_Build_V2:
    stage: build
    only:
      - main
    needs: [CI_Pre_Check] 
    before_script:
      - echo "Build CI_Build_V2 Started"
      - sleep 10
    script:
      - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Test:
    stage: test
    only:
      - main
    when: manual 
    script:
      - docker ps
      - docker images

