# Task 26 - Gitlab CI Trigger

# 1. Download the attached child-pipeline.yml file and upload to your Gitlab Repo.
# 2. Using Trigger in your .gitlab-ci.yml file , add a trigger to the child-pipeline.yml pipeline, 
# so that we can start a downstream pipeline.

trigger_job: #2 - downstream stage
  trigger: 
    include: child-pipeline.yml

default: 
  timeout: 1 hour

stages:
    - pre-check
    - build
    - test

image: docker:latest

CI_Pre_Check:
    stage: pre-check
    only: 
      - main
    allow_failure: true 
    script:
      - docker version 
      - docker ps 
      - docker images ls 
      - sleep 20  
     
CI_Build:
    stage: build
    needs: [] 
    retry: 2
    only: 
      - main
    parallel: 2 # 1
    before_script:
      - echo "Build CI_Build Started"
      - sleep 10
    script:
      - docker build -t $Image_Name:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Build_V2:
    stage: build
    only:
      - main
    needs: [CI_Pre_Check] 
    before_script:
      - echo "Build CI_Build_V2 Started"
      - sleep 10
    script:
      - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Test:
    stage: test
    only:
      - main
    when: manual #3
    script:
      - docker ps
      - docker images
