# Task 16 - Gitlab CI Job Failure 

# 1. Update Script section of CI_Pre_Check Job, and add a one more command "userdump"
# 2. Since there no "userdump" command in linux, our CI_Pre_Check Job will be failed. 
# So monitor the pipeline after updating the Job


stages:
    - pre-check
    - build
    - test

image: docker:latest

CI_Pre_Check:
    stage: pre-check
    only: 
      - main
    script:
      - docker version 
      - docker ps 
      - docker images ls 
      - userdump # 1. To get Job Failure
     
CI_Build:
    stage: build
    only:
      - main
    before_script:
      - echo "Build CI_Build Started"
    script:
      - docker build -t $Image_Name:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Build_V2:
    stage: build
    only:
      - main
    before_script:
      - echo "Build CI_Build_V2 Started"
    script:
      - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Test:
    stage: test
    only:
      - main
    script:
      - docker ps
      - docker images

