# Task 23 - Gitlab CI Timeout

# 1. Remove "Rules" condition from CI_Build Job.
# 2. Add "Only: main" condition in the CI_Build Job.
# 3. Add default section in the pipeline, and in the default section add timeout value of 1 hour.

default: # 3
  timeout: 1 hour

stages:
    - pre-check
    - build
    - test

image: docker:latest

CI_Pre_Check:
    stage: pre-check
    only: 
      - main
    allow_failure: true 
    script:
      - docker version 
      - docker ps 
      - docker images ls 
      - sleep 20  
     
CI_Build:
    stage: build
    needs: [] 
    retry: 2
    only: #2
      - main
    before_script:
      - echo "Build CI_Build Started"
      - sleep 10
    script:
      - docker build -t $Image_Name:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Build_V2:
    stage: build
    only:
      - main
    needs: [CI_Pre_Check] 
    before_script:
      - echo "Build CI_Build_V2 Started"
      - sleep 10
    script:
      - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Test:
    stage: test
    only:
      - main
    script:
      - docker ps
      - docker images
