# Task 19 - Gitlab CI Needs

# 1. Replace the "userdump" command with "sleep 20" in the Script section of CI_Pre_Check job.
# 2. Add "sleep 10" command in the before_Script section of CI_Build and CI_Build_V2 Jobs.
# 3. Allow CI_Build and CI_Build_V2 Jobs to run in parallel, basically make them independent from any other jobs.

stages:
    - pre-check
    - build
    - test

image: docker:latest

CI_Pre_Check:
    stage: pre-check
    only: 
      - main
    allow_failure: true 
    script:
      - docker version 
      - docker ps 
      - docker images ls 
      - sleep 20  # 1
     
CI_Build:
    stage: build
    only:
      - main
    needs: [] # 3. Independent
    before_script:
      - echo "Build CI_Build Started"
      - sleep 10 # 2
    script:
      - docker build -t $Image_Name:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Build_V2:
    stage: build
    only:
      - main
    needs: [] # 3.Independent
    before_script:
      - echo "Build CI_Build_V2 Started"
      - sleep 10
    script:
      - docker build -t $Image_Name_V2:$CI_PIPELINE_IID . 
    after_script:
      - docker images

CI_Test:
    stage: test
    only:
      - main
    script:
      - docker ps
      - docker images

